#theme: netsec007/hacker
#theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: netsec007/hacker
title: netsec007
description: A curated list of resources for all things dev!
