## Docker Compose Example

Docker config location
/Users/cumbia/.docker:/config

compose network
networks:
  default:
    name: my-pre-existing-network
    external: true

or

version: "2.4"
networks:
  outside:
    external:
      name: actual-name-of-network

eg
version: "2.4"

services:
  proxy:
    build: ./proxy
    networks:
      - outside
      - default
  app:
    build: ./app
    networks:
      - default

networks:
  outside:
    external: true
